chore(ci): use action-oc-runner in pr-open

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -104,12 +104,6 @@ runs:
         triggers: ${{ inputs.triggers }}
         diff_branch: ${{ inputs.diff_branch }}
 
-    # Override OpenShift version, if specified
-    - name: Install CLI tools from OpenShift Mirror
-      uses: redhat-actions/openshift-tools-installer@v1
-      with:
-        oc: ${{ inputs.oc_version || '4' }}
-
     # Process variables and inputs
     # Remote/override repo is required if one has been specified (input)
     - name: Checkout remote/override repo
@@ -146,41 +140,46 @@ runs:
 
     - name: Deploy
       if: steps.diff.outputs.triggered == 'true'
-      shell: bash
-      run: |
-        # Expand for deployment steps
+      uses: bcgov/action-oc-runner@X.Y.Z
+      with:
+        oc_namespace: ${{ inputs.OC_NAMESPACE }}
+        oc_server: ${{ inputs.OC_SERVER }}
+        oc_token: ${{ inputs.OC_TOKEN }}
+        triggers: ('frontend/' 'backend/' 'database/')
+        commands: |
+          # Expand for deployment steps
 
-        # Allow pipefail, since we could be catching oc create errors
-        set +o pipefail
+          # Allow pipefail, since we could be catching oc create errors
+          set +o pipefail
 
-        oc login --token=${{ inputs.oc_token }} --server=${{ inputs.oc_server }}
-        oc project ${{ inputs.oc_namespace }} #Safeguard!
+          oc login --token=${{ inputs.oc_token }} --server=${{ inputs.oc_server }}
+          oc project ${{ inputs.oc_namespace }} #Safeguard!
 
-        # Clean any previous ImageStreams
-        IFS=" " read -ra IS <<< "${{ steps.vars.outputs.imageStream }}"
-        for i in "${IS[@]}"
-        do
-          [ ! $(oc get is -o name | grep ^imagestream.image.openshift.io/${i}$) ]|| oc delete is/${i}
-        done
+          # Clean any previous ImageStreams
+          IFS=" " read -ra IS <<< "${{ steps.vars.outputs.imageStream }}"
+          for i in "${IS[@]}"
+          do
+            [ ! $(oc get is -o name | grep ^imagestream.image.openshift.io/${i}$) ]|| oc delete is/${i}
+          done
 
-        # Apply (overwrites) or create (does not overwrite) using processed template
-        TEMPLATE="$(oc process -f ${{ inputs.file }} ${{ inputs.parameters }} --local)"
-        if [ "${{ inputs.overwrite }}" == "true" ]; then
-          oc apply --timeout=${{ inputs.timeout || '15m' }} -f - <<< "${TEMPLATE}"
-        else
-          # Suppress AlreadyExists errors and expected failure
-          oc create -f - 2>&1 <<< "${TEMPLATE}" | sed 's/.*: //'
-        fi
+          # Apply (overwrites) or create (does not overwrite) using processed template
+          TEMPLATE="$(oc process -f ${{ inputs.file }} ${{ inputs.parameters }} --local)"
+          if [ "${{ inputs.overwrite }}" == "true" ]; then
+            oc apply --timeout=${{ inputs.timeout || '15m' }} -f - <<< "${TEMPLATE}"
+          else
+            # Suppress AlreadyExists errors and expected failure
+            oc create -f - 2>&1 <<< "${TEMPLATE}" | sed 's/.*: //'
+          fi
 
-        # Follow any active rollouts; temporary support for DeploymentConfigs
-        DDC=${{ steps.vars.outputs.deployment }}
-        if [ ! -z "${DDC}" ]&&[ ! -z $(oc get deployment ${DDC} -o name --ignore-not-found) ]; then
-          # oc rollout restart deployment/${DDC}
-          oc rollout status deployment/${DDC} -w
-        elif [ ! -z "${DDC}" ]&&[ ! -z $(oc get deploymentconfig ${DDC} -o name --ignore-not-found) ]; then
-          oc rollout status deploymentconfig/${DDC} -w
-        fi
-        
+          # Follow any active rollouts; temporary support for DeploymentConfigs
+          DDC=${{ steps.vars.outputs.deployment }}
+          if [ ! -z "${DDC}" ]&&[ ! -z $(oc get deployment ${DDC} -o name --ignore-not-found) ]; then
+            # oc rollout restart deployment/${DDC}
+            oc rollout status deployment/${DDC} -w
+          elif [ ! -z "${DDC}" ]&&[ ! -z $(oc get deploymentconfig ${DDC} -o name --ignore-not-found) ]; then
+            oc rollout status deploymentconfig/${DDC} -w
+          fi
+
     - name: Route Verification
       if: steps.vars.outputs.url &&
         ( steps.diff.outputs.triggered == 'true' )
