Indent

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -64,7 +64,6 @@ runs:
   using: composite
   steps:
     - shell: bash
-      id: validate
       run: |
         # Validate required inputs
         for input in "file" "oc_namespace" "oc_server" "oc_token"; do
@@ -94,25 +93,24 @@ runs:
         oc_version: ${{ inputs.oc_version }}
         repository: ${{ inputs.repository }}
         triggers: ${{ inputs.triggers }}
-      id: template
-      commands: |
-        # Process template and store for reuse
-        if ! TEMPLATE="$(oc process -f ${{ inputs.file }} ${{ inputs.parameters }} --local)"; then
-          echo "Error: Template processing failed"
-          exit 1
-        fi
-        echo "template=${TEMPLATE}" >> $GITHUB_ENV
-
-        # Extract and clean ImageStreams
-        IS=$(echo "${TEMPLATE}" | jq -r '.items[] | select(.kind=="ImageStream").metadata.name //empty')
-        IFS=" " read -ra IS <<< "${IS}"
-        for i in "${IS[@]}"
-        do
-          if oc get is "${i}" &>/dev/null; then
-            echo "Cleaning up ImageStream ${i}"
-            oc delete is/${i}
+        commands: |
+          # Process template and store for reuse
+          if ! TEMPLATE="$(oc process -f ${{ inputs.file }} ${{ inputs.parameters }} --local)"; then
+            echo "Error: Template processing failed"
+            exit 1
           fi
-        done
+          echo "template=${TEMPLATE}" >> $GITHUB_ENV
+
+          # Remove any conflicting ImageStreams
+          IS=$(echo "${TEMPLATE}" | jq -r '.items[] | select(.kind=="ImageStream").metadata.name //empty')
+          IFS=" " read -ra IS <<< "${IS}"
+          for i in "${IS[@]}"
+          do
+            if oc get is "${i}" &>/dev/null; then
+              echo "Cleaning up ImageStream ${i}"
+              oc delete is/${i}
+            fi
+          done
 
     - uses: bcgov/action-oc-runner@v1.0.0
       id: deploy
@@ -123,42 +121,41 @@ runs:
         oc_version: ${{ inputs.oc_version }}
         repository: ${{ inputs.repository }}
         triggers: ${{ inputs.triggers }}
-      commands: |
-        TEMPLATE="${{ env.template }}"
+        commands: |
+          TEMPLATE="${{ env.template }}"
 
-        if [ "${{ github.event_name == 'pull_request' }}" ]; then
-          echo -e "\nLite mode; skipping HorizontalPodAutoscaler and PodDisruptionBudget objects"
-          TEMPLATE=$(echo "${TEMPLATE}" | jq 'del(.items[] | select(.kind=="HorizontalPodAutoscaler"))')
-          TEMPLATE=$(echo "${TEMPLATE}" | jq 'del(.items[] | select(.kind=="PodDisruptionBudget"))')
+          if [ "${{ github.event_name == 'pull_request' }}" ]; then
+            echo -e "\nLite mode; skipping HorizontalPodAutoscaler and PodDisruptionBudget objects"
+            TEMPLATE=$(echo "${TEMPLATE}" | jq 'del(.items[] | select(.kind=="HorizontalPodAutoscaler"))')
+            TEMPLATE=$(echo "${TEMPLATE}" | jq 'del(.items[] | select(.kind=="PodDisruptionBudget"))')
 
-          echo -e "\nLite mode; limiting deployment replicas to 1"
-          TEMPLATE=$(echo "${TEMPLATE}" | jq '.items |= map(if .kind == "Deployment" then .spec.replicas = 1 else . end)')
+            echo -e "\nLite mode; limiting deployment replicas to 1"
+            TEMPLATE=$(echo "${TEMPLATE}" | jq '.items |= map(if .kind == "Deployment" then .spec.replicas = 1 else . end)')
 
-          echo -e "\nLite mode; limiting deployment strategy to Recreate"
-          TEMPLATE=$(echo "${TEMPLATE}" | jq '.items |= map(if .kind == "Deployment" then .spec.strategy.type = "Recreate" else . end)')
-        fi
+            echo -e "\nLite mode; limiting deployment strategy to Recreate"
+            TEMPLATE=$(echo "${TEMPLATE}" | jq '.items |= map(if .kind == "Deployment" then .spec.strategy.type = "Recreate" else . end)')
+          fi
 
-        if [ "${{ inputs.overwrite }}" != "false" ]; then
-          echo "Overwrite=true; using oc apply"
-          oc apply --timeout=${{ inputs.timeout || '15m' }} -f - <<< "${TEMPLATE}"
-        else
-          # Allow AlreadyExists errors and expected failures
-          echo "Overwrite=false; using oc create"
-          (set +o pipefail; oc create -f - 2>&1 <<< "${TEMPLATE}" | sed 's/.*: //')
-        fi
+          if [ "${{ inputs.overwrite }}" != "false" ]; then
+            echo "Overwrite=true; using oc apply"
+            oc apply --timeout=${{ inputs.timeout || '15m' }} -f - <<< "${TEMPLATE}"
+          else
+            # Allow AlreadyExists errors and expected failures
+            echo "Overwrite=false; using oc create"
+            (set +o pipefail; oc create -f - 2>&1 <<< "${TEMPLATE}" | sed 's/.*: //')
+          fi
 
-        # Deployment and Route Host from template (note: DeploymentConfig is deprecated, but still supported)
-        DEPLOYMENT=$(echo "${TEMPLATE}" | jq '.items[] | select(.kind=="Deployment").metadata.name //empty')
+          # Deployment and Route Host from template (note: DeploymentConfig is deprecated, but still supported)
+          DEPLOYMENT=$(echo "${TEMPLATE}" | jq '.items[] | select(.kind=="Deployment").metadata.name //empty')
 
-        # Follow any active rollouts; temporary support for DeploymentConfigs
-        if [ ! -z "${DEPLOYMENT}" ]&&[ ! -z $(oc get deployment ${DEPLOYMENT} -o name --ignore-not-found) ]; then
-          oc rollout status deployment/${DEPLOYMENT} -w
-        elif [ ! -z "${DEPLOYMENT}" ]&&[ ! -z $(oc get deploymentconfig ${DEPLOYMENT} -o name --ignore-not-found) ]; then
-          oc rollout status deploymentconfig/${DEPLOYMENT} -w
-        fi
+          # Follow any active rollouts; temporary support for DeploymentConfigs
+          if [ ! -z "${DEPLOYMENT}" ]&&[ ! -z $(oc get deployment ${DEPLOYMENT} -o name --ignore-not-found) ]; then
+            oc rollout status deployment/${DEPLOYMENT} -w
+          elif [ ! -z "${DEPLOYMENT}" ]&&[ ! -z $(oc get deploymentconfig ${DEPLOYMENT} -o name --ignore-not-found) ]; then
+            oc rollout status deploymentconfig/${DEPLOYMENT} -w
+          fi
 
     - uses: bcgov/action-oc-runner@v1.0.0
-      id: verify
       with:
         oc_namespace: ${{ inputs.oc_namespace }}
         oc_token: ${{ inputs.oc_token }}
@@ -166,44 +163,44 @@ runs:
         oc_version: ${{ inputs.oc_version }}
         repository: ${{ inputs.repository }}
         triggers: ${{ inputs.triggers }}
-      commands: |
-        function verify_route() {
-          local url=$1
-          local attempts=$2
-          local wait_time=$3
+        commands: |
+          function verify_route() {
+            local url=$1
+            local attempts=$2
+            local wait_time=$3
 
-          for ((i=1; i<=attempts; i++)); do
-            echo "Verification attempt $i of $attempts"
-            if HTTP_CODE=$(curl -Lso /dev/null -w "%{http_code}" "${url}"); then
-              if [ "${HTTP_CODE}" -eq 200 ]; then
-                echo "Route verification successful!"
-                return 0
+            for ((i=1; i<=attempts; i++)); do
+              echo "Verification attempt $i of $attempts"
+              if HTTP_CODE=$(curl -Lso /dev/null -w "%{http_code}" "${url}"); then
+                if [ "${HTTP_CODE}" -eq 200 ]; then
+                  echo "Route verification successful!"
+                  return 0
+                fi
               fi
-            fi
-            echo "HTTP_CODE: ${HTTP_CODE}"
-            [ $i -lt $attempts ] && sleep "${wait_time}"
-          done
-          return 1
-        }
+              echo "HTTP_CODE: ${HTTP_CODE}"
+              [ $i -lt $attempts ] && sleep "${wait_time}"
+            done
+            return 1
+          }
 
-        ROUTE_HOST=$(echo "${{ env.template }}" | jq -r '.items[] | select(.kind=="Route").spec.host //empty')
-        if [ -z "${ROUTE_HOST}" ]; then
-          echo "No route found. Skipping verification."
-          exit 0
-        fi
+          ROUTE_HOST=$(echo "${{ env.template }}" | jq -r '.items[] | select(.kind=="Route").spec.host //empty')
+          if [ -z "${ROUTE_HOST}" ]; then
+            echo "No route found. Skipping verification."
+            exit 0
+          fi
 
-        ROUTE_PATH=${{ inputs.verification_path }}
-        if [ -z "${ROUTE_PATH}" ]; then
-          ROUTE_PATH=$(echo "${{ env.template }}" | jq -r '.items[] | select(.kind=="Route").spec.path //empty')
-        fi
+          ROUTE_PATH=${{ inputs.verification_path }}
+          if [ -z "${ROUTE_PATH}" ]; then
+            ROUTE_PATH=$(echo "${{ env.template }}" | jq -r '.items[] | select(.kind=="Route").spec.path //empty')
+          fi
 
-        URL=$(echo "${ROUTE_HOST}/${ROUTE_PATH}" | sed 's // / g')
-        echo "Verifying route: http://${URL}"
+          URL=$(echo "${ROUTE_HOST}/${ROUTE_PATH}" | sed 's // / g')
+          echo "Verifying route: http://${URL}"
 
-        if ! verify_route "${URL}" ${{ inputs.verification_retry_attempts }} ${{ inputs.verification_retry_seconds }}; then
-          echo "Route verification failed"
-          exit 1
-        fi
+          if ! verify_route "${URL}" ${{ inputs.verification_retry_attempts }} ${{ inputs.verification_retry_seconds }}; then
+            echo "Route verification failed"
+            exit 1
+          fi
 
     - uses: bcgov/action-oc-runner@v1.0.0
       if: inputs.post_rollout != ''
