Allow pipefail on oc create only

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -119,9 +119,9 @@ runs:
             echo "Overwrite=true; using oc apply"
             oc apply --timeout=${{ inputs.timeout || '15m' }} -f - <<< "${TEMPLATE}"
           else
-            # Suppress AlreadyExists errors and expected failure
+            # Allow AlreadyExists errors and expected failure
             echo "Overwrite=false; using oc create"
-            oc create -f - 2>&1 <<< "${TEMPLATE}" | sed 's/.*: //'
+            (set +o pipefail; oc create -f - 2>&1 <<< "${TEMPLATE}" | true)
           fi
 
           # Deployment and Route Host from template (note: DeploymentConfig is deprecated, but still supported)
@@ -130,7 +130,7 @@ runs:
           # Follow any active rollouts; temporary support for DeploymentConfigs
           if [ ! -z "${DDC}" ]&&[ ! -z $(oc get deployment ${DDC} -o name --ignore-not-found) ]; then
             oc rollout status deployment/${DDC} -w
-          elif [ ! -z "${DDC}" ]&&[ ! -z $(oc get deploymentconfig ${DDC} -o name --ignore-not-found) ]; then
+          elif [ ! -z "${DDC}" ]&&[ ! -z $(oc get deploymengaptconfig ${DDC} -o name --ignore-not-found) ]; then
             oc rollout status deploymentconfig/${DDC} -w
           fi
 
